import copy
import pandas as pd
import numpy as np
from typing import Optional, Any

import mass_spectra.utilits.utilits as ms_util
import mass_spectra.brutto.brutto as ms_brutto

def filter_by_rules(gdf: pd.DataFrame) -> pd.DataFrame:
    
    data = copy.deepcopy(gdf)
    temp = copy.deepcopy(data)
    temp = ms_util._merge_isotopes(temp)

    if 'C' not in temp or 'H' not in temp or 'O' not in temp:
        raise Exception('For applying rules in brutto must be CHO elements or their isotopes')
        
    temp['H/C'] = temp['H']/temp['C']
    temp['O/C'] = temp['O']/temp['C']
    data = data.loc[(temp['H/C'] < 2.2) & (temp['H/C'] > 0.25) & (temp['O/C'] < 1)]

    if 'N' not in temp:
        temp['N'] = 0
        
    temp['DBE-O'] = 1.0 + temp["C"] - 0.5 * temp["H"] + 0.5 * temp['N'] - temp['O'] # type: ignore
    data = data.loc[temp['DBE-O'] <= 10]
        
    if 'N' in temp:
        temp['parity'] = (temp['H'] + temp['N'])%2
        data = data.loc[temp['parity']==0]
    
    return data

def assign_optimized(data: pd.DataFrame,
            brutto_dict: Any|None = None,
            generated_bruttos_table: Optional[pd.DataFrame] = None,
            rel_error: float|None = None,
            abs_error: float|None = None,
            sign: str ='-',
            mass_min: Optional[float] =  None,
            mass_max: Optional[float] = None,
            intensity_min: Optional[float] =  None,
            intensity_max: Optional[float] = None,
            charge_max: int = 1,
            nitrogen_precision_factor: float = 2.0,
            sulfur_precision_factor: float = 2.0
    ) -> pd.DataFrame:
        """
        Assigning brutto formulas to signal by mass
        
        Parameters
        -----------
        brutto_dict: dict
            Optional. Deafault None.
            Custom Dictonary for generate brutto table.
            Example: {'C':(4, 51),'H':(4, 101),'O':(0,26), 'N':(0,4), 'C_13':(0,3)}
        generated_bruttos_table: pandas DataFrame 
            Optional. Contain column 'mass' and elements, 
            should be sorted by 'mass'.
            Can be generated by function brutto_generator.brutto_gen(). 
            if 'None' generate table with default elemnets and ranges
            C: 4-50, H 4-100, O 0-25, N 0-3, S 0-2.
        rel_error: float
            Optional. default 0.5, permissible error in ppm for assign mass to brutto formulas
        abs_error: float
            Optional. default None, permissible absolute error for assign mass to brutto formulas
        sign: str
            Optional. Deafult '-'.
            Mode in which mass spectrum was gotten. 
            '-' for negative mode
            '+' for positive mode
            '0' for neutral
        mass_min: float
            Optional. Default None. Minimall mass for assigment
        mass_max: float
            Optional. Default None. Maximum mass for assigment
        intensity_min: float
            Optional. Default None. Minimall intensity for assigment
        intensity_max: float
            Optional. Default None. Maximum intensity for assigment
        charge_max: int
            Maximum charge in m/z. Default 1.
        nitrogen_precision_factor: float
            Optional. Default 2.0. Factor by which to increase precision for formulas containing nitrogen
        sulfur_precision_factor: float
            Optional. Default 2.0. Factor by which to increase precision for formulas containing sulfur

        Return
        ------
        pd.DataFrame 
        """

        name = data.attrs['name']

        if generated_bruttos_table is None:
            generated_bruttos_table = ms_brutto.brutto_gen(brutto_dict)

        if mass_min is None:
            mass_min = data['mass'].min()
        if mass_max is None:
            mass_max = data['mass'].max()
        if intensity_min is None:
            intensity_min = data['intensity'].min()
        if intensity_max is None:
            intensity_max = data['intensity'].max()
        
        if sign == '-':
            mass_shift = - 0.00054858 + 1.007825  # electron and hydrogen mass
        elif sign == '+':
            mass_shift = 0.00054858  # electron mass
        elif sign == '0':
            mass_shift = 0
        else:
            raise Exception('Sended sign to assign method is not correct. May be "+","-","0"')

        data.attrs['sign'] = sign

        if rel_error is not None and abs_error is not None:
            raise Exception('one of rel_error or abs_error must be None in assign method')
        
        if rel_error is not None:
            rel = True
            
        elif abs_error is not None:
            rel = False
        else:
            rel = True
            rel_error = 0.5  

        data = data.loc[:,['mass', 'intensity']].reset_index(drop=True)


        elems = list(generated_bruttos_table.drop(columns=["mass"]))

        # 1. Подготовка данных в NumPy
        target_masses = data['mass'].to_numpy()
        target_intensities = data['intensity'].to_numpy()
        ref_masses = generated_bruttos_table["mass"].to_numpy()
        
        # Элементы и их маски
        elems = [e for e in generated_bruttos_table.columns if e != 'mass']
        ref_elements = generated_bruttos_table[elems].values
        
        n_idx = elems.index('N') if 'N' in elems else -1
        s_idx = elems.index('S') if 'S' in elems else -1
        
        # Предрассчитаем маски для азота и серы в справочнике
        has_n = ref_elements[:, n_idx] > 0 if n_idx != -1 else np.zeros(len(ref_masses), dtype=bool)
        has_s = ref_elements[:, s_idx] > 0 if s_idx != -1 else np.zeros(len(ref_masses), dtype=bool)
        has_special = has_n | has_s

        # Итоговые массивы для хранения результатов
        final_assign = np.zeros(len(data), dtype=bool)
        final_charge = np.ones(len(data), dtype=int)
        final_elements = np.zeros((len(data), len(elems)))

        # Фильтр по диапазонам (делаем один раз маской)
        valid_mask = (target_masses >= mass_min) & (target_masses <= mass_max) & \
            (target_intensities >= intensity_min) & (target_intensities <= intensity_max)

        # 2. Основной цикл только по зарядам (их мало!)
        for charge in range(1, charge_max + 1):
            if final_assign.all(): break # Если всё уже приписали, выходим
            
            # Еще не приписанные и входящие в диапазоны
            todo_mask = valid_mask & (~final_assign)
            if not todo_mask.any(): continue
            
            m = (target_masses[todo_mask] + mass_shift) * charge
            
            # Векторный поиск ближайших индексов
            idx = np.searchsorted(ref_masses, m)
            idx = np.clip(idx, 0, len(ref_masses) - 1)
            # Проверка соседа слева
            idx_left = np.clip(idx - 1, 0, len(ref_masses) - 1)
            dist_right = np.abs(ref_masses[idx] - m)
            dist_left = np.abs(ref_masses[idx_left] - m)
            best_idx = np.where(dist_left < dist_right, idx_left, idx)
            
            # Расчет ошибок
            diffs = np.abs(ref_masses[best_idx] - m)
            if rel:
                errors = diffs / m * 1e6
            else:
                errors = diffs
            
            # Применяем факторы точности
            precision_limit = np.full(len(m), (rel_error if rel else abs_error) / charge) # type: ignore
            
            # У ужесточаем лимит для N и S
            mask_special = has_special[best_idx]
            if n_idx != -1:
                precision_limit = np.where(has_n[best_idx], precision_limit / nitrogen_precision_factor, precision_limit)
            if s_idx != -1:
                precision_limit = np.where(has_s[best_idx], precision_limit / sulfur_precision_factor, precision_limit)
                
            # Условие успеха
            hits = errors <= precision_limit
            
            # Записываем результат
            # Получаем индексы исходного массива data, которые "выстрелили"
            global_indices = np.where(todo_mask)[0][hits]
            best_ref_indices = best_idx[hits]
            
            final_assign[global_indices] = True
            final_charge[global_indices] = charge
            final_elements[global_indices] = ref_elements[best_ref_indices]

        # 3. Сборка результата
        res_df = pd.DataFrame(final_elements, columns=elems)
        res_df['assign'] = final_assign
        res_df['charge'] = final_charge
        
        # Объединяем с исходными массами
        out = pd.concat([data[['mass', 'intensity']], res_df], axis=1)
        out.attrs['name'] = name
        return out
